# Generated by Django 5.2.6 on 2025-11-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimensiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensiones',
            options={'verbose_name': 'Dimensión', 'verbose_name_plural': 'Dimensiones'},
        ),
    ]
