# Generated by Django 5.2.6 on 2025-11-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0006_alter_actividad_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubActividad',
            fields=[
                ('sub_actividad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('grado_aprobacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actividad', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sub_actividades', to='actividades.actividad')),
            ],
            options={
                'verbose_name': 'SubActividad',
                'verbose_name_plural': 'SubActividades',
            },
        ),
    ]
