# Generated by Django 5.2.6 on 2025-11-03 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_actividad_accion_id_actividad_estado_and_more'),
        ('sub_actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subactividad',
            name='actividad_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='sub_actividades', to='actividades.actividad'),
        ),
    ]
