# Generated by Django 5.2.6 on 2025-11-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_actividades', '0002_subactividad_actividad_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subactividad',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='subactividad',
            name='id',
        ),
        migrations.AddField(
            model_name='subactividad',
            name='sub_actividad_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subactividad',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
