# Generated by Django 5.2.6 on 2025-11-03 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_actividad_accion_id_actividad_estado_and_more'),
        ('sub_actividades', '0002_subactividad_actividad_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subactividad',
            name='actividad_id',
        ),
        migrations.AlterField(
            model_name='subactividad',
            name='actividad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='sub_actividades', to='actividades.actividad'),
        ),
    ]
