# Generated by Django 5.2.6 on 2025-11-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_actividades', '0003_remove_subactividad_actividad_remove_subactividad_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subactividad',
            old_name='actividad_id',
            new_name='actividad',
        ),
    ]
