# Generated by Django 5.2.6 on 2025-11-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_alter_actividad_options'),
        ('sub_actividades', '0004_rename_actividad_id_subactividad_actividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subactividad',
            options={'verbose_name': 'SubActividad', 'verbose_name_plural': 'SubActividades'},
        ),
        migrations.AlterField(
            model_name='subactividad',
            name='actividad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sub_actividades', to='actividades.actividad'),
        ),
    ]
