# Generated by Django 5.2.6 on 2025-10-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='presupuesto_reajustado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
