# Generated by Django 5.2.6 on 2025-10-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0003_verificacionaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificacionaccion',
            name='id',
        ),
        migrations.AddField(
            model_name='verificacionaccion',
            name='verificacion_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
