# Generated by Django 5.2.6 on 2025-11-03 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0004_remove_verificacionaccion_id_and_more'),
        ('dimensiones', '0001_initial'),
        ('usuarios', '0003_alter_usuarios_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='accion',
            name='dimension',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='acciones', to='dimensiones.dimensiones'),
        ),
        migrations.AddField(
            model_name='accion',
            name='responsable',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='acciones_responsable', to='usuarios.usuarios'),
        ),
    ]
