# Generated by Django 5.2.6 on 2025-11-03 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0005_accion_dimension_accion_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacionaccion',
            name='accion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones', to='acciones.accion'),
        ),
    ]
