# Generated by Django 5.2.6 on 2025-11-03 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0007_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='accion',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='acciones', to='acciones.estados'),
        ),
    ]
