# Generated by Django 5.2.6 on 2025-11-04 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0009_poblar_estados'),
        ('dimensiones', '0002_alter_dimensiones_options'),
        ('usuarios', '0007_alter_usuarios_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accion',
            options={'verbose_name': 'Acción', 'verbose_name_plural': 'Acciones'},
        ),
        migrations.AlterField(
            model_name='accion',
            name='dimension',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='dimensiones.dimensiones'),
        ),
        migrations.AlterField(
            model_name='accion',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='acciones.estados'),
        ),
        migrations.AlterField(
            model_name='accion',
            name='responsable',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='acciones_responsable', to='usuarios.usuarios'),
        ),
    ]
