# Generated by Django 5.2.6 on 2025-11-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='usuario_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
