# Generated by Django 5.2.6 on 2025-11-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_roles_remove_usuarios_id_usuarios_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.roles'),
        ),
    ]
