# Generated by Django 5.2.6 on 2025-11-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_poblar_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='temporal123', max_length=128),
            preserve_default=False,
        ),
    ]
