# Generated by Django 5.2.6 on 2025-11-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_poblar_usuarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
