# Generated by Django 5.2.6 on 2025-10-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiales_solicitados', models.CharField(max_length=50)),
                ('numero_orden', models.CharField(max_length=15)),
                ('valor_esperado', models.IntegerField()),
                ('valor_final', models.IntegerField()),
                ('codigo_factura', models.CharField(max_length=25)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
