# Generated by Django 5.2.6 on 2025-10-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmaterial',
            name='valor_final',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
