# Generated by Django 5.2.6 on 2025-10-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_materiales', '0002_alter_solicitudmaterial_valor_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudmaterial',
            name='id',
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='solicitud_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitudmaterial',
            name='codigo_factura',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
