# Generated by Django 5.2.6 on 2025-10-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_materiales', '0003_remove_solicitudmaterial_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmaterial',
            name='numero_orden',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
