# Generated by Django 5.2.6 on 2025-11-04 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_remove_actividad_accion_id_actividad_accion_and_more'),
        ('solicitud_materiales', '0005_solicitudmaterial_actividad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmaterial',
            name='actividad_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_materiales', to='actividades.actividad'),
        ),
    ]
