# Generated by Django 5.2.6 on 2025-11-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_materiales', '0006_alter_solicitudmaterial_actividad_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudmaterial',
            old_name='actividad_id',
            new_name='actividad',
        ),
    ]
