# Generated by Django 5.2.6 on 2025-10-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacionActividad',
            fields=[
                ('verificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('url', models.URLField()),
            ],
        ),
    ]
