# Generated by Django 5.2.6 on 2025-11-03 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0008_accion_estado'),
        ('actividades', '0002_verificacionactividad'),
        ('usuarios', '0003_alter_usuarios_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='accion_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='acciones.accion'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='acciones.estados'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='responsable',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='actividades_responsable', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='verificacionactividad',
            name='actividad_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='verificaciones', to='actividades.actividad'),
        ),
    ]
