# Generated by Django 5.2.6 on 2025-11-04 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0010_alter_accion_options_alter_accion_dimension_and_more'),
        ('actividades', '0003_actividad_accion_id_actividad_estado_and_more'),
        ('usuarios', '0007_alter_usuarios_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='accion_id',
        ),
        migrations.AddField(
            model_name='actividad',
            name='accion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='acciones.accion'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='acciones.estados'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='responsable',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_responsable', to='usuarios.usuarios'),
        ),
        migrations.AlterField(
            model_name='verificacionactividad',
            name='actividad_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones', to='actividades.actividad'),
        ),
    ]
