# Generated by Django 5.2.6 on 2025-11-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_remove_actividad_accion_id_actividad_accion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificacionactividad',
            old_name='actividad_id',
            new_name='actividad',
        ),
    ]
