# Generated by Django 5.2.6 on 2025-11-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_rename_actividad_id_verificacionactividad_actividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
    ]
